[2024-09-14T17:11:25.103+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-14T17:11:25.190+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbnb_model.data_analysis scheduled__2024-09-13T00:00:00+00:00 [queued]>
[2024-09-14T17:11:25.209+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbnb_model.data_analysis scheduled__2024-09-13T00:00:00+00:00 [queued]>
[2024-09-14T17:11:25.210+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-09-14T17:11:25.250+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): data_analysis> on 2024-09-13 00:00:00+00:00
[2024-09-14T17:11:25.272+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'airbnb_model', 'data_analysis', 'scheduled__2024-09-13T00:00:00+00:00', '--job-id', '664', '--raw', '--subdir', 'DAGS_FOLDER/air_price_pred_dag.py', '--cfg-path', '/tmp/tmpvh8gfpla']
[2024-09-14T17:11:25.277+0000] {standard_task_runner.py:105} INFO - Job 664: Subtask data_analysis
[2024-09-14T17:11:25.354+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=498) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-14T17:11:25.355+0000] {standard_task_runner.py:72} INFO - Started process 499 to run task
[2024-09-14T17:11:25.478+0000] {task_command.py:467} INFO - Running <TaskInstance: airbnb_model.data_analysis scheduled__2024-09-13T00:00:00+00:00 [running]> on host fb744bf0dc86
[2024-09-14T17:11:26.037+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Denis' AIRFLOW_CTX_DAG_ID='airbnb_model' AIRFLOW_CTX_TASK_ID='data_analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T00:00:00+00:00'
[2024-09-14T17:11:26.040+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-14T17:11:26.279+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-09-14T17:11:26.283+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --deploy-mode client /opt/***/dags/air_data_analysis.py
[2024-09-14T17:11:32.564+0000] {spark_submit.py:579} INFO - Using properties file: null
[2024-09-14T17:11:32.844+0000] {spark_submit.py:579} INFO - Parsed arguments:
[2024-09-14T17:11:32.845+0000] {spark_submit.py:579} INFO - master                  spark://spark-master:7077
[2024-09-14T17:11:32.846+0000] {spark_submit.py:579} INFO - remote                  null
[2024-09-14T17:11:32.847+0000] {spark_submit.py:579} INFO - deployMode              client
[2024-09-14T17:11:32.848+0000] {spark_submit.py:579} INFO - executorMemory          null
[2024-09-14T17:11:32.849+0000] {spark_submit.py:579} INFO - executorCores           null
[2024-09-14T17:11:32.850+0000] {spark_submit.py:579} INFO - totalExecutorCores      null
[2024-09-14T17:11:32.851+0000] {spark_submit.py:579} INFO - propertiesFile          null
[2024-09-14T17:11:32.853+0000] {spark_submit.py:579} INFO - driverMemory            null
[2024-09-14T17:11:32.855+0000] {spark_submit.py:579} INFO - driverCores             null
[2024-09-14T17:11:32.856+0000] {spark_submit.py:579} INFO - driverExtraClassPath    null
[2024-09-14T17:11:32.857+0000] {spark_submit.py:579} INFO - driverExtraLibraryPath  null
[2024-09-14T17:11:32.858+0000] {spark_submit.py:579} INFO - driverExtraJavaOptions  null
[2024-09-14T17:11:32.859+0000] {spark_submit.py:579} INFO - supervise               false
[2024-09-14T17:11:32.861+0000] {spark_submit.py:579} INFO - queue                   null
[2024-09-14T17:11:32.862+0000] {spark_submit.py:579} INFO - numExecutors            null
[2024-09-14T17:11:32.863+0000] {spark_submit.py:579} INFO - files                   null
[2024-09-14T17:11:32.864+0000] {spark_submit.py:579} INFO - pyFiles                 null
[2024-09-14T17:11:32.865+0000] {spark_submit.py:579} INFO - archives                null
[2024-09-14T17:11:32.866+0000] {spark_submit.py:579} INFO - mainClass               null
[2024-09-14T17:11:32.867+0000] {spark_submit.py:579} INFO - primaryResource         file:/opt/***/dags/air_data_analysis.py
[2024-09-14T17:11:32.869+0000] {spark_submit.py:579} INFO - name                    arrow-spark
[2024-09-14T17:11:32.872+0000] {spark_submit.py:579} INFO - childArgs               []
[2024-09-14T17:11:32.873+0000] {spark_submit.py:579} INFO - jars                    null
[2024-09-14T17:11:32.875+0000] {spark_submit.py:579} INFO - packages                null
[2024-09-14T17:11:32.876+0000] {spark_submit.py:579} INFO - packagesExclusions      null
[2024-09-14T17:11:32.878+0000] {spark_submit.py:579} INFO - repositories            null
[2024-09-14T17:11:32.879+0000] {spark_submit.py:579} INFO - verbose                 true
[2024-09-14T17:11:32.881+0000] {spark_submit.py:579} INFO - 
[2024-09-14T17:11:32.882+0000] {spark_submit.py:579} INFO - Spark properties used, including those specified through
[2024-09-14T17:11:32.884+0000] {spark_submit.py:579} INFO - --conf and those from the properties file null:
[2024-09-14T17:11:32.885+0000] {spark_submit.py:579} INFO - (spark.master,spark://spark-master:7077)
[2024-09-14T17:11:32.888+0000] {spark_submit.py:579} INFO - 
[2024-09-14T17:11:32.890+0000] {spark_submit.py:579} INFO - 
[2024-09-14T17:11:33.755+0000] {spark_submit.py:579} INFO - Main class:
[2024-09-14T17:11:33.756+0000] {spark_submit.py:579} INFO - org.apache.spark.deploy.PythonRunner
[2024-09-14T17:11:33.757+0000] {spark_submit.py:579} INFO - Arguments:
[2024-09-14T17:11:33.759+0000] {spark_submit.py:579} INFO - file:/opt/***/dags/air_data_analysis.py
[2024-09-14T17:11:33.760+0000] {spark_submit.py:579} INFO - null
[2024-09-14T17:11:33.764+0000] {spark_submit.py:579} INFO - Spark config:
[2024-09-14T17:11:33.765+0000] {spark_submit.py:579} INFO - (spark.app.name,arrow-spark)
[2024-09-14T17:11:33.766+0000] {spark_submit.py:579} INFO - (spark.app.submitTime,1726333893715)
[2024-09-14T17:11:33.767+0000] {spark_submit.py:579} INFO - (spark.master,spark://spark-master:7077)
[2024-09-14T17:11:33.768+0000] {spark_submit.py:579} INFO - (spark.submit.deployMode,client)
[2024-09-14T17:11:33.769+0000] {spark_submit.py:579} INFO - (spark.submit.pyFiles,)
[2024-09-14T17:11:33.771+0000] {spark_submit.py:579} INFO - Classpath elements:
[2024-09-14T17:11:33.772+0000] {spark_submit.py:579} INFO - 
[2024-09-14T17:11:33.773+0000] {spark_submit.py:579} INFO - 
[2024-09-14T17:11:33.774+0000] {spark_submit.py:579} INFO - 
[2024-09-14T17:11:35.821+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:35 INFO SparkContext: Running Spark version 3.5.2
[2024-09-14T17:11:35.850+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:35 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-09-14T17:11:35.853+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:35 INFO SparkContext: Java version 17.0.12
[2024-09-14T17:11:36.117+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-09-14T17:11:36.520+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO ResourceUtils: ==============================================================
[2024-09-14T17:11:36.522+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-09-14T17:11:36.523+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO ResourceUtils: ==============================================================
[2024-09-14T17:11:36.524+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO SparkContext: Submitted application: Airbnb_regr_model
[2024-09-14T17:11:36.617+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-09-14T17:11:36.653+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO ResourceProfile: Limiting resource is cpu
[2024-09-14T17:11:36.655+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-09-14T17:11:36.855+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO SecurityManager: Changing view acls to: ***
[2024-09-14T17:11:36.859+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO SecurityManager: Changing modify acls to: ***
[2024-09-14T17:11:36.860+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO SecurityManager: Changing view acls groups to:
[2024-09-14T17:11:36.862+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO SecurityManager: Changing modify acls groups to:
[2024-09-14T17:11:36.865+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:36 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-09-14T17:11:37.524+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:37 INFO Utils: Successfully started service 'sparkDriver' on port 39189.
[2024-09-14T17:11:37.648+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:37 INFO SparkEnv: Registering MapOutputTracker
[2024-09-14T17:11:37.753+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:37 INFO SparkEnv: Registering BlockManagerMaster
[2024-09-14T17:11:37.791+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:37 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-09-14T17:11:37.793+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:37 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-09-14T17:11:37.802+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:37 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-09-14T17:11:37.861+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:37 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-f1c7ce39-f3ef-4867-952b-04e44e49cd6c
[2024-09-14T17:11:37.897+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:37 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-09-14T17:11:37.937+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:37 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-09-14T17:11:38.326+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:38 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-09-14T17:11:38.551+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:38 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-09-14T17:11:39.053+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO Executor: Starting executor ID driver on host fb744bf0dc86
[2024-09-14T17:11:39.068+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO Executor: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-09-14T17:11:39.069+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO Executor: Java version 17.0.12
[2024-09-14T17:11:39.096+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2024-09-14T17:11:39.099+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@2b2d567f for default.
[2024-09-14T17:11:39.232+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46375.
[2024-09-14T17:11:39.234+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO NettyBlockTransferService: Server created on fb744bf0dc86:46375
[2024-09-14T17:11:39.239+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-09-14T17:11:39.288+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, fb744bf0dc86, 46375, None)
[2024-09-14T17:11:39.302+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO BlockManagerMasterEndpoint: Registering block manager fb744bf0dc86:46375 with 434.4 MiB RAM, BlockManagerId(driver, fb744bf0dc86, 46375, None)
[2024-09-14T17:11:39.314+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, fb744bf0dc86, 46375, None)
[2024-09-14T17:11:39.318+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:39 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, fb744bf0dc86, 46375, None)
[2024-09-14T17:11:43.036+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:43 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-09-14T17:11:43.475+0000] {spark_submit.py:579} INFO - 24/09/14 17:11:43 INFO SharedState: Warehouse path is 'file:/user/hive/warehouse'.
[2024-09-14T17:11:52.230+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 233, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 284, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2358, in refresh_from_db
    _refresh_from_db(task_instance=self, session=session, lock_for_update=lock_for_update)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 872, in _refresh_from_db
    ti = TaskInstance.get_task_instance(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2344, in get_task_instance
    return query.one_or_none()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-14T17:11:54.451+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-09-14T17:12:59.728+0000] {job.py:229} INFO - Heartbeat recovered after 77.63 seconds
[2024-09-14T17:13:03.485+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-09-14T17:13:03.487+0000] {spark_submit.py:579} INFO - File "/opt/***/dags/air_data_analysis.py", line 15, in <module>
[2024-09-14T17:13:03.494+0000] {spark_submit.py:579} INFO - df = spark.read.csv(data_path, header=True, inferSchema=True, sep=';', encoding='cp1251')
[2024-09-14T17:13:03.496+0000] {spark_submit.py:579} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-14T17:13:03.498+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/sql/readwriter.py", line 740, in csv
[2024-09-14T17:13:03.502+0000] {spark_submit.py:579} INFO - return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2024-09-14T17:13:03.504+0000] {spark_submit.py:579} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-09-14T17:13:03.508+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2024-09-14T17:13:03.512+0000] {spark_submit.py:579} INFO - return_value = get_return_value(
[2024-09-14T17:13:03.514+0000] {spark_submit.py:579} INFO - ^^^^^^^^^^^^^^^^^
[2024-09-14T17:13:03.516+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
[2024-09-14T17:13:03.522+0000] {spark_submit.py:579} INFO - raise converted from None
[2024-09-14T17:13:03.578+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/opt/***/Airbnb.csv.
[2024-09-14T17:13:03.890+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:03 INFO SparkContext: Invoking stop() from shutdown hook
[2024-09-14T17:13:03.894+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:03 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-09-14T17:13:04.029+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:04 INFO SparkUI: Stopped Spark web UI at http://fb744bf0dc86:4040
[2024-09-14T17:13:04.144+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:04 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-09-14T17:13:04.302+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:04 INFO MemoryStore: MemoryStore cleared
[2024-09-14T17:13:04.304+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:04 INFO BlockManager: BlockManager stopped
[2024-09-14T17:13:04.364+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:04 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-09-14T17:13:04.382+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:04 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-09-14T17:13:04.459+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:04 INFO SparkContext: Successfully stopped SparkContext
[2024-09-14T17:13:04.461+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:04 INFO ShutdownHookManager: Shutdown hook called
[2024-09-14T17:13:04.465+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-e689322d-689d-474b-a3b6-04bf388cc62b
[2024-09-14T17:13:04.483+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-bb4be689-a9d8-442b-a5bd-1eb33b8a0c1f/pyspark-075375e4-6c1c-49cf-bdcc-46de4caecbc1
[2024-09-14T17:13:04.505+0000] {spark_submit.py:579} INFO - 24/09/14 17:13:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-bb4be689-a9d8-442b-a5bd-1eb33b8a0c1f
[2024-09-14T17:13:04.764+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --deploy-mode client /opt/***/dags/air_data_analysis.py. Error code is: 1.
[2024-09-14T17:13:04.856+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=airbnb_model, task_id=data_analysis, run_id=scheduled__2024-09-13T00:00:00+00:00, execution_date=20240913T000000, start_date=20240914T171125, end_date=20240914T171304
[2024-09-14T17:13:04.985+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-14T17:13:04.987+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 664 for task data_analysis (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --deploy-mode client /opt/***/dags/air_data_analysis.py. Error code is: 1.; 499)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --deploy-mode client /opt/***/dags/air_data_analysis.py. Error code is: 1.
[2024-09-14T17:13:05.067+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-14T17:13:05.146+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-14T17:13:05.153+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
