[2024-09-12T20:18:40.001+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T20:18:40.096+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_find_makers_dag.spark_submit_task scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-12T20:18:40.137+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_find_makers_dag.spark_submit_task scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-12T20:18:40.139+0000] {taskinstance.py:2865} INFO - Starting attempt 9 of 12
[2024-09-12T20:18:40.225+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2024-09-11 00:00:00+00:00
[2024-09-12T20:18:40.245+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=511) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-12T20:18:40.250+0000] {standard_task_runner.py:72} INFO - Started process 512 to run task
[2024-09-12T20:18:40.249+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_find_makers_dag', 'spark_submit_task', 'scheduled__2024-09-11T00:00:00+00:00', '--job-id', '484', '--raw', '--subdir', 'DAGS_FOLDER/spark_sql_dag.py', '--cfg-path', '/tmp/tmp4c53qfaq']
[2024-09-12T20:18:40.251+0000] {standard_task_runner.py:105} INFO - Job 484: Subtask spark_submit_task
[2024-09-12T20:18:40.399+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_find_makers_dag.spark_submit_task scheduled__2024-09-11T00:00:00+00:00 [running]> on host e10d33bf7907
[2024-09-12T20:18:40.653+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Denis' AIRFLOW_CTX_DAG_ID='spark_find_makers_dag' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T00:00:00+00:00'
[2024-09-12T20:18:40.656+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T20:18:40.781+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-09-12T20:18:40.786+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --name arrow-spark --verbose --deploy-mode client /opt/***/dags/spark_job.py
[2024-09-12T20:18:45.804+0000] {spark_submit.py:579} INFO - Using properties file: null
[2024-09-12T20:18:46.094+0000] {spark_submit.py:579} INFO - Parsed arguments:
[2024-09-12T20:18:46.096+0000] {spark_submit.py:579} INFO - master                  spark://spark-master:7077
[2024-09-12T20:18:46.098+0000] {spark_submit.py:579} INFO - remote                  null
[2024-09-12T20:18:46.100+0000] {spark_submit.py:579} INFO - deployMode              client
[2024-09-12T20:18:46.102+0000] {spark_submit.py:579} INFO - executorMemory          null
[2024-09-12T20:18:46.103+0000] {spark_submit.py:579} INFO - executorCores           null
[2024-09-12T20:18:46.105+0000] {spark_submit.py:579} INFO - totalExecutorCores      null
[2024-09-12T20:18:46.107+0000] {spark_submit.py:579} INFO - propertiesFile          null
[2024-09-12T20:18:46.109+0000] {spark_submit.py:579} INFO - driverMemory            null
[2024-09-12T20:18:46.110+0000] {spark_submit.py:579} INFO - driverCores             null
[2024-09-12T20:18:46.112+0000] {spark_submit.py:579} INFO - driverExtraClassPath    null
[2024-09-12T20:18:46.113+0000] {spark_submit.py:579} INFO - driverExtraLibraryPath  null
[2024-09-12T20:18:46.115+0000] {spark_submit.py:579} INFO - driverExtraJavaOptions  null
[2024-09-12T20:18:46.116+0000] {spark_submit.py:579} INFO - supervise               false
[2024-09-12T20:18:46.118+0000] {spark_submit.py:579} INFO - queue                   null
[2024-09-12T20:18:46.120+0000] {spark_submit.py:579} INFO - numExecutors            null
[2024-09-12T20:18:46.122+0000] {spark_submit.py:579} INFO - files                   null
[2024-09-12T20:18:46.123+0000] {spark_submit.py:579} INFO - pyFiles                 null
[2024-09-12T20:18:46.125+0000] {spark_submit.py:579} INFO - archives                null
[2024-09-12T20:18:46.127+0000] {spark_submit.py:579} INFO - mainClass               null
[2024-09-12T20:18:46.128+0000] {spark_submit.py:579} INFO - primaryResource         file:/opt/***/dags/spark_job.py
[2024-09-12T20:18:46.129+0000] {spark_submit.py:579} INFO - name                    arrow-spark
[2024-09-12T20:18:46.131+0000] {spark_submit.py:579} INFO - childArgs               []
[2024-09-12T20:18:46.133+0000] {spark_submit.py:579} INFO - jars                    null
[2024-09-12T20:18:46.134+0000] {spark_submit.py:579} INFO - packages                null
[2024-09-12T20:18:46.136+0000] {spark_submit.py:579} INFO - packagesExclusions      null
[2024-09-12T20:18:46.138+0000] {spark_submit.py:579} INFO - repositories            null
[2024-09-12T20:18:46.140+0000] {spark_submit.py:579} INFO - verbose                 true
[2024-09-12T20:18:46.141+0000] {spark_submit.py:579} INFO - 
[2024-09-12T20:18:46.143+0000] {spark_submit.py:579} INFO - Spark properties used, including those specified through
[2024-09-12T20:18:46.144+0000] {spark_submit.py:579} INFO - --conf and those from the properties file null:
[2024-09-12T20:18:46.146+0000] {spark_submit.py:579} INFO - (spark.master,spark://spark-master:7077)
[2024-09-12T20:18:46.148+0000] {spark_submit.py:579} INFO - 
[2024-09-12T20:18:46.149+0000] {spark_submit.py:579} INFO - 
[2024-09-12T20:18:47.009+0000] {spark_submit.py:579} INFO - Main class:
[2024-09-12T20:18:47.011+0000] {spark_submit.py:579} INFO - org.apache.spark.deploy.PythonRunner
[2024-09-12T20:18:47.012+0000] {spark_submit.py:579} INFO - Arguments:
[2024-09-12T20:18:47.013+0000] {spark_submit.py:579} INFO - file:/opt/***/dags/spark_job.py
[2024-09-12T20:18:47.015+0000] {spark_submit.py:579} INFO - null
[2024-09-12T20:18:47.017+0000] {spark_submit.py:579} INFO - Spark config:
[2024-09-12T20:18:47.019+0000] {spark_submit.py:579} INFO - (spark.app.name,arrow-spark)
[2024-09-12T20:18:47.021+0000] {spark_submit.py:579} INFO - (spark.app.submitTime,1726172326970)
[2024-09-12T20:18:47.022+0000] {spark_submit.py:579} INFO - (spark.master,spark://spark-master:7077)
[2024-09-12T20:18:47.024+0000] {spark_submit.py:579} INFO - (spark.submit.deployMode,client)
[2024-09-12T20:18:47.025+0000] {spark_submit.py:579} INFO - (spark.submit.pyFiles,)
[2024-09-12T20:18:47.027+0000] {spark_submit.py:579} INFO - Classpath elements:
[2024-09-12T20:18:47.029+0000] {spark_submit.py:579} INFO - 
[2024-09-12T20:18:47.030+0000] {spark_submit.py:579} INFO - 
[2024-09-12T20:18:47.032+0000] {spark_submit.py:579} INFO - 
[2024-09-12T20:18:49.709+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:49 INFO SparkContext: Running Spark version 3.5.2
[2024-09-12T20:18:49.719+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:49 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-09-12T20:18:49.721+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:49 INFO SparkContext: Java version 17.0.12
[2024-09-12T20:18:49.975+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-09-12T20:18:50.399+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO ResourceUtils: ==============================================================
[2024-09-12T20:18:50.401+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-09-12T20:18:50.403+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO ResourceUtils: ==============================================================
[2024-09-12T20:18:50.405+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO SparkContext: Submitted application: SparkJob
[2024-09-12T20:18:50.506+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-09-12T20:18:50.539+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO ResourceProfile: Limiting resource is cpu
[2024-09-12T20:18:50.542+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-09-12T20:18:50.803+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO SecurityManager: Changing view acls to: ***
[2024-09-12T20:18:50.806+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO SecurityManager: Changing modify acls to: ***
[2024-09-12T20:18:50.809+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO SecurityManager: Changing view acls groups to:
[2024-09-12T20:18:50.811+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO SecurityManager: Changing modify acls groups to:
[2024-09-12T20:18:50.813+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:50 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-09-12T20:18:51.777+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:51 INFO Utils: Successfully started service 'sparkDriver' on port 42343.
[2024-09-12T20:18:51.896+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:51 INFO SparkEnv: Registering MapOutputTracker
[2024-09-12T20:18:52.060+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:52 INFO SparkEnv: Registering BlockManagerMaster
[2024-09-12T20:18:52.204+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:52 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-09-12T20:18:52.207+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:52 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-09-12T20:18:52.229+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:52 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-09-12T20:18:52.326+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:52 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-8482bb5e-4ae8-4b33-ae63-95b29ce7447a
[2024-09-12T20:18:52.372+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:52 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-09-12T20:18:52.427+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:52 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-09-12T20:18:52.888+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:52 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-09-12T20:18:53.089+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-09-12T20:18:53.422+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO Executor: Starting executor ID driver on host e10d33bf7907
[2024-09-12T20:18:53.428+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO Executor: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-09-12T20:18:53.434+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO Executor: Java version 17.0.12
[2024-09-12T20:18:53.466+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2024-09-12T20:18:53.469+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@2b2d567f for default.
[2024-09-12T20:18:53.541+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38397.
[2024-09-12T20:18:53.543+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO NettyBlockTransferService: Server created on e10d33bf7907:38397
[2024-09-12T20:18:53.552+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-09-12T20:18:53.576+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, e10d33bf7907, 38397, None)
[2024-09-12T20:18:53.588+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO BlockManagerMasterEndpoint: Registering block manager e10d33bf7907:38397 with 434.4 MiB RAM, BlockManagerId(driver, e10d33bf7907, 38397, None)
[2024-09-12T20:18:53.600+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, e10d33bf7907, 38397, None)
[2024-09-12T20:18:53.604+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:53 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, e10d33bf7907, 38397, None)
[2024-09-12T20:18:55.102+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:55 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-09-12T20:18:55.131+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:55 INFO SharedState: Warehouse path is 'file:/user/hive/warehouse'.
[2024-09-12T20:18:58.193+0000] {spark_submit.py:579} INFO - 24/09/12 20:18:58 INFO InMemoryFileIndex: It took 128 ms to list leaf files for 1 paths.
[2024-09-12T20:19:04.436+0000] {spark_submit.py:579} INFO - 24/09/12 20:19:04 INFO InMemoryFileIndex: It took 9 ms to list leaf files for 1 paths.
[2024-09-12T20:19:06.187+0000] {spark_submit.py:579} INFO - Final Table:
[2024-09-12T20:19:07.486+0000] {spark_submit.py:579} INFO - 24/09/12 20:19:07 INFO FileSourceStrategy: Pushed Filters: IsNotNull(Type),EqualTo(Type,PC)
[2024-09-12T20:19:07.505+0000] {spark_submit.py:579} INFO - 24/09/12 20:19:07 INFO FileSourceStrategy: Post-Scan Filters: isnotnull(type#16),(type#16 = PC)
[2024-09-12T20:19:07.534+0000] {spark_submit.py:579} INFO - 24/09/12 20:19:07 INFO FileSourceStrategy: Pushed Filters: IsNotNull(MODEL)
[2024-09-12T20:19:07.536+0000] {spark_submit.py:579} INFO - 24/09/12 20:19:07 INFO FileSourceStrategy: Post-Scan Filters: isnotnull(model#1)
[2024-09-12T20:20:07.923+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 139, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-09-12T20:20:58.949+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
